server:
  servlet:
    context-path: /test
spring:
  datasource:
    password: 123
    url: jdbc:oracle:thin:@localhost:1521/orcle
    username: SYSTEM
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
